import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const smoochSans = localFont({
  src: "../public/Fonts/SmoochSans.ttf",
  variable: "--font-smooch-sans",
  display: "swap",
});

const onyx = localFont({
  src: "../public/Fonts/Onyx.otf",
  variable: "--font-onyx",
  display: "swap",
});

const edwardianScript = localFont({
  src: "../public/Fonts/edwardianscriptitc.ttf",
  variable: "--font-edwardian-script",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${smoochSans.variable} ${onyx.variable} ${edwardianScript.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
